version: '3'

services:
  todoapi:
    image: paolosalvatori/todoapi:latest
    deploy:
      mode: replicated
      replicas: 5
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RepositoryService__CosmosDb__EndpointUri=https://todoapi.documents.azure.com:443/
      - RepositoryService__CosmosDb__PrimaryKey=Document-Db-Primary-Key
      - RepositoryService__CosmosDb__DatabaseName=TodoApiDb
      - RepositoryService__CosmosDb__CollectionName=TodoApiCollection
      - NotificationService__ServiceBus__ConnectionString=Azure-Service-Bus-Connection-String
      - NotificationService__ServiceBus__QueueName=todoapi
      - ApplicationInsights__InstrumentationKey=Application-Insights-Instrumentation-Key
    ports:
      - "8081:80"

  todoweb:
    image: paolosalvatori/todoweb:latest
    deploy:
      mode: replicated
      replicas: 5
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - TodoApiService__EndpointUri=todoapi.todoapp:8081
      - ApplicationInsights__InstrumentationKey=Application-Insights-Instrumentation-Key
    ports:
      - "8082:80"